### PR TITLE
Some updates for version 1.1.5

### PR DESCRIPTION
**Pull request by williamdes**
- Merged #23 
- Merged #29 
- Merged #33 
- Merged #35 

- Some minor improvements

### CODE REVIEW

**Comment by williamdes** [comment]
@kayahr I made https://github.com/williamdes/jquery-fullscreen-plugin/tree/npm/1.1.4 so you could npm publish the version

And I hope my changes are okay, If so you can merge my pull-request and all the other ones will be merged.
It is ready for a npm publish of `1.1.5`.

https://www.npmjs.com/package/jquery-fullscreen-plugin

**Comment by williamdes** [comment]
@kayahr did you see my pull-request ?

**Comment by williamdes** [comment]
@kayahr :ping_pong: If you did have a chance to see my PR ?

**Comment by kayahr** [comment]
Sorry for the late answer. Well... the problem is... This project is pretty old, I haven't used jquery and this plugin for years. So I'm not really able to check the pull request as you (who is still using jquery and this plugin) have now more know how about the topic then I have (or ever had). 

Are you interested in taking over the project? I would be glad to transfer it to you.

**Comment by williamdes** [comment]
> Sorry for the late answer. Well... the problem is... This project is pretty old, I haven't used jquery and this plugin for years. So I'm not really able to check the pull request as you (who is still using jquery and this plugin) have now more know how about the topic then I have (or ever had).
> 
> Are you interested in taking over the project? I would be glad to transfer it to you.

Yeah, sure
Could you also give me access to https://www.npmjs.com/package/jquery-fullscreen-plugin ?

**Comment by kayahr** [comment]
Transfer failed because your account already has a fork of the project obviously. Could you rename your copy first? And I can't give you access to the NPM package because it wasn't me who uploaded it. I don't know the guy who did.

**Comment by williamdes** [comment]
> Transfer failed because your account already has a fork of the project obviously. Could you rename your copy first? And I can't give you access to the NPM package because it wasn't me who uploaded it. I don't know the guy who did.

Done ;)

**Comment by williamdes** [comment]
> And I can't give you access to the NPM package because it wasn't me who uploaded it. I don't know the guy who did.

I will have to contact him ..

**Comment by kayahr** [comment]
Still doesn't work because of your fork. Well, I still like to transfer it so github automatically redirects requests to the old repository to the new one... Hm... Well, I guess your first action is merging the PR anyway so I'll do that now, then you can remove your fork and then I hope I can transfer it.

**Comment by williamdes** [comment]
Could you transfer it to @code-lts ?

**Comment by williamdes** [comment]
I created this organisation to hold packages for a long term support, so I can give the hand to someone else in some years of needed

**Comment by kayahr** [comment]
Transfer worked now after merging the PRs. I guess you have to accept the transfer now? I never transfered a project to someone else :)

**Comment by kayahr** [comment]
It worked! Great. Well, thanks for taking over, I hope the project is in good hands. Treat it well and be nice to it, jQuery can be quirky from time to time ;-)

**Comment by williamdes** [comment]
Thank you !
It worked fine after I accepted it, I also invited you to @code-lts that I will improve

**Pull request merged**
